### ISSUE TITLE
Target "The device you speak to" for Media Player: Play Media - Content Type: Routine

### ISSUE THREAD

**Issue by rhoskins61** [alandtse/alexa_media_player#1984]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Not really related to a problem :)

**Describe the solution you'd like**
Currently, we can target any Alexa device to TTS, play media or fire a routine (brilliant), etc. However, it would be great if we could target the last echo device that was invoked (I currently have 20 echo devices in the house). Even though the Alexa Routine itself has the option to report via "The device you speak to", you still have to target a device to execute a generic routine in HA. If this does exist or if there is a workaround, I can't find it. 

**Describe alternatives you've considered**

**Additional context**

**Comment by figorr** [comment]
Maybe you can set up “the last echo sensor”.

[https://github.com/custom-components/alexa_media](url)

It works fine, but sometimes it takes a while (a couple of seconds) to update due Amazon’s Server.  😪
 So, you can use a small delay in your automations to solve it.

**Comment by rhoskins61** [comment]
Thank you. Yeah, the delay is so variable, it's fairly useless.  Was hoping for maybe another attribute.

Cheers!

**Comment by danielbrunt57** [comment]
Apparently, the underlying problem is Alexa does not actively publish or push her info.  alexa_media_player has to poll Alexa for the info and therein lies the problem.  How often do you automatically poll without causing a shutdown of services?  If you try and poll every second, Amazon would just say "Enough of that!" and close the door.  A while ago, last_alexa would update resonably quickly but that caused a problem as the notify service is removed and recreated in HA and would frequently cause error in scripts if they happened to be calling the routine while it was updating with the result being "service does not exist".  The current version of AMP now forces us to initiate the poll via alexa_media.update_last_called and no longer automatically updates it.  If you engage a different alexa in your environment, the HA's entities never change, at least mine don't now.  If we do not run alexa_media.update_last_called then notify.alexa_media_last_called never changes nor do the last_called attributes of the devices.  The problem then becomes one of "How do I know you've finished your update?".  You can listen for `event_type: service_registered, data: domain: notify, service: alexa_media_last_called` but that never occurs if Alexa's last device has not changed so we're back to a delay with a hardcoded timeout.  Also, the timestamps on the HA Echo entities never change either.  The notify.alexa_media_last_called just silently finishes if no change needs to be made.  If it could fire an HA event or update timestamps, either when a succesful update has been done or when it's finished early as there was nothing to do, then we could check for that and would not have to add a fixed delay to our scripts.
<end-of-rant>

**Comment by danielbrunt57** [comment]
With the recent updates to alexa_media_player (notably the HTTP2 implementation), sensor.last_alexa now updates almost instantly.  This is my templated sensor which includes the last called media player's `last_called_timestamp`:
```
  - name: Last Alexa
    unique_id: last_alexa
    state: |-
      {{ states.media_player | selectattr('attributes.last_called','eq',true) | map(attribute='entity_id') | first | default(none) }}
    availability: |-
      {{ states.media_player | selectattr('attributes.last_called','eq',true) | map(attribute='attributes.last_called_timestamp') | first is defined }}
    attributes:
      last_called_timestamp: |-
        {{ states.media_player | selectattr('attributes.last_called','eq',true) | map(attribute='attributes.last_called_timestamp') | first | default(none) }}
```
The `name:` could also be templated as follows but I found it confusing when looking at automations & scripts in visual mode as HA now displayes the friendly name rather than entity_id.
```
- name: "{{ states.media_player | selectattr('attributes.last_called','eq',true) | map(attribute='name') | first | default(none) }}"
```
Although I ended up never using it, I also implemented the Universal Media Player integration in a similar fashion,
If you need to specify a `media_player` entity rather than a sensor and want the last alexa media_player, this would work:
```
  - platform: universal
    name: "Last Alexa"
    unique_id: media_player.last_alexa
    state_template: "{{ states.media_player|selectattr('attributes.last_called','eq',true)|map(attribute='entity_id') | first | default(none) }}"
```

**Comment by danielbrunt57** [comment]
It would seem I spoke too soon about last_called_timestamp updating almost instantly.
Yesterday it was instant, today it's updating after about 5 minutes. Sigh......

**Comment by juan11perez** [comment]
good day it appears Amazon has implemented some change and the attribute "last_called=None" is not working

**Comment by danielbrunt57** [comment]
Yeah, it seems to update itself about once every hour or two. I've had to go back to invoking the service call to update last_alexa in my scripts & automations. PITA...

**Comment by Morpheus2018** [comment]
> Yeah, it seems to update itself about once every hour or two. I've had to go back to invoking the service call to update last_alexa in my scripts & automations. PITA...

Everything worked until last night, now it is "last_called: null", "last_called_timestamp: null", "last_called_summary: null"

![entität_last_alexa](https://github.com/custom-components/alexa_media_player/assets/37088587/cc3f681c-a32a-41cd-9f38-fbb8c9f8a074)
![verlauf_last_alexa](https://github.com/custom-components/alexa_media_player/assets/37088587/c45b5e07-6e4c-4496-8f4c-71920a034ace)

All settings in configuration.yaml / template.yaml actually have to be correct.!?
```
echos:
  name: All Echos
  entities:
    - media_player.alexa_echo_dot
    - media_player.home_fire_tab
    - media_player.this_device_2

    template:
      - sensor:
          - name: last_alexa
            state: >
              {{ expand('group.echos') | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
            availability: >
              {{ expand('group.echos') | selectattr('attributes.last_called','eq',True) | first is defined }}

```
Is the problem just with me or with Amazon?

**Comment by danielbrunt57** [comment]
I don't use a manual group like you have.  I use this sensor template:
```
  - name: Last Alexa
    unique_id: last_alexa
    state: >
      {{ states.media_player | selectattr('attributes.last_called','eq',true) | map(attribute='entity_id') | first | default(none) }}
    availability: >
      {{ states.media_player | selectattr('attributes.last_called','eq',true) | map(attribute='attributes.last_called_timestamp') | first is defined }}
    attributes:
      last_called_timestamp: >
        {{ states.media_player | selectattr('attributes.last_called','eq',true) | map(attribute='attributes.last_called_timestamp') | first | default(none) }}
      actual_friendly_name: >
        {{ states.media_player | selectattr('attributes.last_called','eq',true) | map(attribute='attributes.friendly_name') | first | default(none) }}
 ```

**Comment by danielbrunt57** [comment]
I also have configured the [HA universal media player integration](https://www.home-assistant.io/integrations/universal/) which gives me this:
![image](https://github.com/custom-components/alexa_media_player/assets/49846893/afaa73cb-1885-420d-a15c-9554c56c0df5)
```
  - platform: universal
    name: "Last Alexa"
    unique_id: media_player.last_alexa
    state_template: "{{ states.media_player|selectattr('attributes.last_called','eq',true)|map(attribute='entity_id') | first | default(none) }}"
```

**Comment by Morpheus2018** [comment]
> I don't use a manual group like you have. I use this sensor template:....

Thanks for the quick answer, but unfortunately it doesn't work with any single "sensor template", whether with " {{ states.media_player | .... " or " {{ expand('group.echos') | .... " because there are echoes everywhere: media_player.home_fire_tab "last_called: null", "last_called_timestamp: null", "last_called_summary: null" 
I think that's the problem!?

![media_player last_alexa](https://github.com/custom-components/alexa_media_player/assets/37088587/5a070316-abf8-428c-a7fc-294279ab6b33)

**Comment by Morpheus2018** [comment]
> I also have configured the [HA Universal Media Player integration](https://www.home-assistant.io/integrations/universal/) which 

why is media_player.home_fire_tab "last_called: null", "last_called_timestamp: null", "last_called_summary: null"
or
```
{{ states.media_player|selectattr('attributes.last_called','eq',true)|map(attribute='entity_id') | first | default(none) }} = None
or
 state: >
 {{ expand('group.all_alexa_echos') | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
availability: >
 {{ expand('group.all_alexa_echos') | selectattr('attributes.last_called','eq',True) | first is defined }}
=
state: >
               
 availability: >
 False
```

**Comment by Morpheus2018** [comment]
does it still work for you? 
that's what I mean!
notify.alexa_media_last_called service no longer recognised by Home Assistant #2090

**Comment by danielbrunt57** [comment]
Yes, everything is fine here in Canada (AWS region: us-east-1).

**Comment by grillp** [comment]
It looks like Amazon have deprecated the API/page that AMP used to identify the Last Called media_player and update the attributes.. 

As someone mentioned above, AMP could use one of teh API's on the Review Voice History page (https://www.amazon.com.au/alexa-privacy/apd/rvh). This calls an API to retrieve the last commands for the day using 
https://www.amazon.com.au/alexa-privacy/apd/rvh/customer-history-records-v2?startTime=1698498000000&endTime=1698560298865&disableGlobalNav=false where the startTime and EndTime parameters need to be adjusted according tho the time.

Is anyone working on the fix for this?

**Comment by grillp** [comment]
Soneone has opened an issue on this in AlexaPy: https://gitlab.com/keatontaylor/alexapy/-/issues/27

**Comment by danielbrunt57** [comment]
I've noticed that as of now, `volume_level` and `is_muted` update real-time but none of the other attibutes update until polled and am scratching my head as to why...

**Comment by dgarozzo** [comment]
Based on the [SSML](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html) markup, you should be able to use the prosody markup tag to set the volume, but it doesn't work with Alexa Media Player for some reason.

```html
<speak>
    This is how I normally speak.
    <amazon:emotion name="disappointed" intensity="high">
        This is how I speak when I am disappointed.
        <prosody volume="x-loud">Now I am telling you I am disappointed very loudly!</prosody>
    </amazon:emotion>
</speak>
```
