### ISSUE TITLE
Alexa media player timeout during system startup - alexaapi.get_customer_history_records Timeout error/CancelledError 'Global task timeout'

### ISSUE THREAD

**Issue by davidepanato** [alandtse/alexa_media_player#2132]
**Describe the bug**

HA startup is extremely slow waiting for Alexa media player to start. Errors are present in the home assistant log related to the component. When system is up some functionalities are working i.e. service to reproduce tts on amazon echo

**To Reproduce**

ha startup

**Expected behavior**

startup should not block while loading Alexa media player component, no errors should be present

**Screenshots**

N/A

**System details**

- Home-assistant (version): 2023.11.3
- alexa_media (version from `const.py` or HA startup): 4.8.0
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : YES

**Logs**
[home-assistant.log](https://github.com/alandtse/alexa_media_player/files/13551377/home-assistant.log)

**Additional context**

**Comment by ronaldjeremy** [comment]
Same, issue started after recently updating HA.

**Comment by djcrawleravp** [comment]
Same issue here (even-though the integration works perfectly after)

<img width="643" alt="Screen Shot 2023-12-07 at 17 40 28" src="https://github.com/alandtse/alexa_media_player/assets/12896341/cec0efcd-a8ea-4c5e-a08d-a6715250b3f6">

**Comment by mwav3** [comment]
Last_alexa seems to have stopped working a few weeks ago, so I've worked around it. Hanging up the startup of home assistant for at least 5 minutes each time because it is trying to get it to load is now a pretty big issue- for that 5 minutes automations in Home assistant and many other devices don't work for me. It's  definitely a problem when I'm testing/changing things in home assistant which requires frequent restarts, and a lot of waiting now.

**Comment by alandtse** [comment]
I'm open to a PR moving it out of the init. The media player refresh across all echos can also be moved out.

**Comment by mwav3** [comment]
Removing/commenting out this line 188 from the init appears to clear the hangup at startup now

```
 await update_last_called(login_obj)
```

I could submit a PR to remove that line to get things moving again, but I'm not an expert in python coding so am just wondering if I would be missing something else here...  Haven't looked into the refresh changes either.

**Comment by alandtse** [comment]
It probably needs more work than just commenting it out to be honest. The refresh I believe uses the same function. The only difference is HA doesn't block everything during the refresh.

**Comment by mwav3** [comment]
Do you think the "last called" will ever work again?  If there's a chance it might come back what do you think about adding a "timeout" if it fails instead?  This solves the 5 minute hangup, with just a 10 second timeout, and a log error for the timeout.  I added the timeout at line 753

```
        if not last_called or not (last_called and last_called.get("summary")):
            try:
                async with async_timeout.timeout(10):
                    last_called = await AlexaAPI.get_last_device_serial(login_obj)
```
Otherwise if you think last called is gone forever a lot of things will have to be updated to completely remove references to it

**Comment by alandtse** [comment]
No idea what Amazon is planning nor do I know whether it's region specific. I guess a timeout may help. We're already hitting the task timeout so tightening it may be ok.

**Comment by bryeartem** [comment]
> No idea what Amazon is planning nor do I know whether it's region specific. I guess a timeout may help. We're already hitting the task timeout so tightening it may be ok.

Just an FYI, My last_alexa sensor has still been working (US-NE) it has definitely been slower over the last year or so than it was when the sensor was first added... but it does indeed still work for me... it would be disappointing if they removed it entirely because I have a lot of stuff that relies on that sensor to figure out what room/device you are trying to control.

**Comment by 3ative** [comment]
Weird that some peeps are having a such a delay - My HA restarts in just over 1 minute.
