### ISSUE TITLE
Captcha doesn't work / repeats indefinitely

### ISSUE THREAD

**Issue by Aaroneisele55** [alandtse/alexa_media_player#2136]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When I try to sign in, the captcha doesn't work. 
When I successfully solve it, a new one appears and so on.
This prevents me from signing in.

**To Reproduce**

Sign in using a .de account

**Expected behavior**

I should be able to sign in normally

**Screenshots**

![Screenshot_20231208_050658_Firefox](https://github.com/alandtse/alexa_media_player/assets/87670899/83e1c22c-8fa6-44f1-8b46-12883955e48c)

**System details**

- Home-assistant (version): 2023.12
- alexa_media (version from `const.py` or HA startup): 4.8.0
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : n

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

It doesn't work over both the external (Tailscale) and the internal address.

**Comment by tyanai** [comment]
Same here.

**Comment by 9dnsb** [comment]
Same

**Comment by alandtse** [comment]
See #2103. Amazon wants you to use a different browser.

**Comment by Aaroneisele55** [comment]
> See #2103. Amazon wants you to use a different browser.

I did get to the "blue" login page but when I ebtered the data (**correctly!**), it gave me a 503 error

**Comment by alandtse** [comment]
Btw 2FA is mandatory. Please enable.

**Comment by MrsXenchen** [comment]
> See #2103. Amazon wants you to use a different browser.

In different browser I get 500 error: #2138. There the tipp was to use chrome which ends up in repeating captca.

**Comment by Ximerox** [comment]
+1

**Comment by Goeste** [comment]
+1 here.

.de account. got the blue login screen, bt am stuck in a loop of captchas... local ip is used sonce HA is not reachable from the outside world

**Comment by ettim** [comment]
I'm also stuck on captcha loop with amazon.it , firefox and W10 (Local HA ip)

**Comment by paulte** [comment]
I'm also experiencing the same issue.

Did a fresh HA install a few days ago along with media player 3.8.1 and everything worked fine.

Just done another fresh HA install and am getting stuck in a captcha loop.

HA versions:
Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

Alexa Media Player Version - 4.8.1 (now have to manually chose an older version due to the requirement for a beta HA version)

Have done multiple restarts / reboots to ensure a stable / clean starting point.

Entering the following details on the main page:
* amazon email for amazon.co.uk
* password
* setting domain to amazon.co.uk
* HA url set to nabucasa fqdn https:///....nabu.casa/
* Creating a new backup method / app within amazon 2SV settings
* Copying 13 * 4 char barcode from amazon into HA
* Copying OTP from HA into amazon

at this point, I get stuck in an endless loop of captchas.

This setup has been done from a Mac/Chrome private browswing session so no existing cookies to conflict.

After confirming the OTP, I do get an email from amazon saying an authenticator app has been successfully added.

**Comment by Matsuo3rd** [comment]
I've been there guys. Was trying to get this integration working through countless tries and always ended to this captcha loop. I could not find the underlying root cause ... but it finally decided to work under HA 2014.1.0. My assumptions is that this is coming from Amazon rather than anything. I am using Amazon France instance (amazon.fr) - worth noting as I saw many complains coming from non-US (de, it) users.

Here is the procedure I executed ... but again, this is the same one I executed so many times without success:
. Using Safari (macOS) during the whole process (regular mode = no need for incognito)
. Upgrade HA to latest (2014.1.0 back then)
. Disable / Wipe out 2FA Amazon
. Re-enable 2FA Amazon (using Safari/macOS as 2FA token generator)
. Upgrade alexa-media-player to latest (4.9.0) through HACS
. Restart HA
. Follow steps in https://www.youtube.com/watch?v=giyo6Pv3GLo (as suggested in another ticket, I am not speaking German but this is pretty self explanatory)
. Voilà!
