### ISSUE TITLE
401: Unauthorized when trying to setup initial login

### ISSUE THREAD

**Issue by tyanai** [alandtse/alexa_media_player#2137]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When trying to login, right after the amazon screen for supplying the user/password, I'm getting a white screen with text "401: Unauthorized" instead of getting the Captcha Screen.  Seems HomeAssistant also mark this as a failure login attempt to homeassistant itself, as after 3 retries it bans me from accessing HA altogether.

**To Reproduce**

1. Go to 'Add Integration'
2. Click on 'Alexa Media Player'
3. fill in the user/password, amazon.com and the long key for the 2FA
4. Approve the generated token in in sync with I see in the app and click 'submit'
5. Now fill in the Amazon user/password and click submit

**Expected behavior**

You should see the Captcha screen, but instead you are getting "401: Unauthorized" error.

**System details**

- Home-assistant (version): 2023.12.0
- alexa_media (version from `const.py` or HA startup): Latest
- alexapy (version from `pip show alexapy` or HA startup): "Package not found alexapy"
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : **Yes**

**Logs**
Attached.
[home-assistant_alexa.log](https://github.com/alandtse/alexa_media_player/files/13612659/home-assistant_alexa.log)

**Comment by Stuke00** [comment]
I’m getting the same thing.

**Comment by tyanai** [comment]
I was able to finish the wizard successfully after the upgrade of HA Core to 2023.12.1

I made it from my iphone using chrome.

**Comment by mhoogenbosch** [comment]
I have the same problem, I only started trying this plugin until the first beta of 2023.12. I created the following community post. https://community.home-assistant.io/t/cant-get-alexa-media-player-working-from-the-netherlands/650182

It seems with 2023.12.1 the behavior has changed. But in all cases I now end in an endless loop of CAPCHA.

What I tried:
- Login with amazon.com, and https://externalurl.com (which resolves nicely internally)
- Login with amazon.com and http://192.168.1.1:8123
- Login with amazon.co.uk, and https://externalurl.com (which resolves nicely internally)
- Login with amazon.co.uk and http://192.168.1.1:8123

I'm not really sure of what i need to use. The alexa dot is set to English british as languange because this is recommended for dutch. But my account is in Amazon.com as far as I know.
