### ISSUE TITLE
Requires a 2024.xxx version?

### ISSUE THREAD

**Issue by Jeppedy** [alandtse/alexa_media_player#2159]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
Update issues:
1) Alexa Media Player says an update is available, but when going to the update screen, it just spins and doesn't allow the update.

2) Attempting to re-download the Alexa HACS integration says a 2024.xxx HA version is required.

**To Reproduce**

1. Go to HACS
2. Click on Redownload
3. See 2024.xxx requirement 

**Expected behavior**
Allow redownload

**Screenshots**
![Screenshot_2024-01-02-08-54-56-40_c3a231c25ed346e59462e84656a70e50](https://github.com/alandtse/alexa_media_player/assets/7842787/132b86b1-476d-4262-a976-8b71054912eb)
![Screenshot_2024-01-02-08-50-59-26_c3a231c25ed346e59462e84656a70e50](https://github.com/alandtse/alexa_media_player/assets/7842787/232f1a7e-d7bd-4c89-a677-dead02f7f94e)

**System details**
On latest public release 2023.12.xxx

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alams154** [comment]
From what I understand, this is desired behavior as the 2024.01.X beta for Home Assistant slightly changes how media players are handled.

There was some work done (#2150, #2149) to update the Alexa Media Player integration to match the new standard which I believe is not backwards compatible with previous versions of Home Assistant.  For that reason, HACS is preventing the download since the integration will most likely not work with your current version of Home Assistant (new stable release of Home Assistant should be out tomorrow).

You could potentially try the [manual method](https://github.com/alandtse/alexa_media_player/wiki/Configuration#manual-mode) of pulling the custom_components directory from this repo into your Home Assistant instance to verify that the current version of the integration is/isn't supported by Home Assistant 2023.12.X.

**Comment by alandtse** [comment]
Not a bug from us. HACS is failing to hide the version. It is correctly preventing the install if you're on an older version of HA.
