### ISSUE TITLE
Version 4.11.x broke "Include devices connected via Echo" functionality

### ISSUE THREAD

**Issue by KC-inDomus** [alandtse/alexa_media_player#2344]
**Describe the bug**

As in the title, latest versions 4.11.x broke "Include devices connected via Echo" functionality. Flag won't stay selected and no device is discovered.

**To Reproduce**

Use latest versions.

**System details**

- Home-assistant (version): 2024.7.3
- alexa_media (version from `const.py` or HA startup): latest
- alexapy (version from `pip show alexapy` or HA startup): latest
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes, 2FA is enabled

**Logs**
No details are logged.

**Comment by alandtse** [comment]
@danielbrunt57

**Comment by danielbrunt57** [comment]
4.11.2 was writing the new setting to core.config_entries but a re-edit was displaying the default settings rather than the value in config_entries.  4.11.4 fixes this.  However, it's currently looking to me like a manual reload of the integration is required to enable the new settings.  I see an update listener which is _supposed_ to reload the integration entry when settings are reconfigured but it looks like it might not be working, hence why I'm saying a manual reload may be necessary at this point.  I added a _LOGGER.info line in my live code, restarted, edited the config and it completed and recalls the new setting now but I did not see an alexa_media info log entry in HA.  Still debugging...

**Comment by SConaway** [comment]
I'm still encountering an issue with the new version. I tried re-editing the settings as well as removing and re-adding the integration, but it doesn't seem to work for me.

I added `_LOGGER.error("it is set to %s", config_entry.options.get(CONF_EXTENDED_ENTITY_DISCOVERY))` to `__init__.py:320`, and it always prints None, no matter what I set in the GUI. Overriding the initial value seems to make everything work now:

```diff
--- 4.11.4/custom_components/alexa_media/__init__.py
+++ changed/custom_components/alexa_media/__init__.py
@@ -309,9 +309,7 @@ async def async_setup_entry(hass, config_entry):
                 CONF_PUBLIC_URL: config_entry.options.get(
                     CONF_PUBLIC_URL, DEFAULT_PUBLIC_URL
                 ),
-                CONF_EXTENDED_ENTITY_DISCOVERY: config_entry.options.get(
-                    CONF_EXTENDED_ENTITY_DISCOVERY, DEFAULT_EXTENDED_ENTITY_DISCOVERY
-                ),
+                CONF_EXTENDED_ENTITY_DISCOVERY: True,
                 CONF_DEBUG: config_entry.options.get(CONF_DEBUG, False),
             },
             DATA_LISTENER: [config_entry.add_update_listener(update_listener)],
```
Strangely enough, the GUI seems to be handling it fine, as the value is now persisted between edit sessions. I can turn it off, save, (restart HA), edit again and it's off, or turn it on and then it'll be on.

**Comment by danielbrunt57** [comment]
> I added `_LOGGER.error("it is set to %s", config_entry.options.get(CONF_EXTENDED_ENTITY_DISCOVERY))` to `__init__.py:320`,

Thanks! and I saw the issue. before reading your post.
It **_used_** to be under the [options] key but it is now under the [data] key as are all of the hass.data[DATA_ALEXAMEDIA]["accounts"].setdefault() options!  That's why the data coordinator was not being triggered & reloading the config entry as it never saw options {} change.  I've got that working now but am still trying to figure out why HTTP2 push is not updating last_alexa.  

![image](https://github.com/user-attachments/assets/b6ef4196-c1cc-4d6f-8f35-90985cb048e6)

I'm seeing http2push coming in when I speak to an alexa but nothing about last_alexa...

![image](https://github.com/user-attachments/assets/847d48c6-71c9-43df-9906-3e07693f0176)

**Comment by qu4nd** [comment]
Fixed for me with 4.11.5 👍🏻

**Comment by KC-inDomus** [comment]
Confirmed, 4.11.5 solved the problem. Thanks guys :)

**Comment by Moxser** [comment]
Hi everyone. For me the latest update 4.11.5 broke the IQA. Can anyone help me?
