### ISSUE TITLE
Temperature sensors become unavailable after first scan interval due to `Login error detected; not contacting API`

### ISSUE THREAD

**Issue by abhayms-git** [alandtse/alexa_media_player#2441]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
After the recent update, i see that "temperature" entity for the Echo devices are no longer available.
I have had this working and have connected automations 

Is the access to "temperature" entity been removed?

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/02e786eb-5f8c-455b-8ef1-9724c0d16449)

**System details**

- Home-assistant (version): 
- alexa_media (version from `const.py` or HA startup): 4.12.7
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by R1200G** [comment]
Look at issue #2440 

https://github.com/alandtse/alexa_media_player/issues/2440#issuecomment-2276839248

**Comment by danielbrunt57** [comment]
Enable the option "Include Devices connected via Echo"...

**Comment by eduardokabello** [comment]
Even if I enable the option “Include Devices connected via Echo”, the temperature entity isn't shown. All other entity is shown, except temperature entity. By the way, I reinstall the integration from scratch, but this issue maintains.

**Comment by figorr** [comment]
I tried by enabling the option "Include Devices connected via Echo" and after a while … the entities came back (it is not immediate). But after some minutes the entities became unavailable again.
The only warnings I found at logs …
```
2024-08-09 21:36:51.744 WARNING (MainThread) [alexapy.helpers] alexaapi.get_customer_history_records((<alexapy.alexalogin.AlexaLogin object at 0x7f9e899f8e90>,), {'max_record_size': 10}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Unauthorized',)

2024-08-09 21:36:51.745 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f9e899f8e90>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Unauthorized',)

2024-08-09 21:38:05.813 WARNING (MainThread) [alexapy.helpers] alexaapi.get_dnd_state((<alexapy.alexalogin.AlexaLogin object at 0x7f9e899f8e90>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',) 
```
First I updated HA Core from 2024.7.4 to 2024.8.0
And then I updated AMP from 4.12.3 to 4.12.7

The “last called” service seems not to be working too. When I call the service or even when I talk to any echo … seems to appear these warnings at logs.

**Comment by danielbrunt57** [comment]
I also noticed last night that the last called service is not working but I've not had time to investigate nor will I for the next 2-3 days...

**Comment by ChristophCaina** [comment]
Maybe, this does help for getting the Temperature Sensor back:

I've set up a test system of HA with 2024.8.0 and a fresh installation of Alexa_media_Player.
Everything was working, except the temperature sensor.

![grafik](https://github.com/user-attachments/assets/481d9e03-e89e-4e72-969d-7e81e3e5e1cb)

Since the temperature sensor is still working on my production installation, there's one difference in the installation.

I tried to reconfigure the integration and checked the following setting - which was set on my production system, but not on the test system.
![grafik](https://github.com/user-attachments/assets/69445fea-0200-41a5-9295-289d023423da)

After the integration did reload, the temp-sensor was available:
![grafik](https://github.com/user-attachments/assets/b50a5abb-72da-4ab8-9039-2d41bb7ce560)

**Comment by tonka3000** [comment]
I have the same issue. Mostly it is unavailable.

**Comment by eduardokabello** [comment]
> Edit: I deleted the file “config/.storage/alexa_media.<config_entry_identifier>.pickle”, then shutdown HA and started again after a minute. Once HA started the AMP integration asked to reconfigure … and after confirming again the credentials and the OTP password … the integration seems working fine. No new warnings at logs by the moment. All the temperature sensors are available and being updated. And the “last called service” looks it is OK too.

I tried it, but in my case, the temperature entity insists on not being shown.

**Comment by figorr** [comment]
> I tried it, but in my case, the temperature entity insists on not being shown.

You are right this morning when I wake up, I saw the temp entities were unavailable again, and the “Alexa last called service” didn’t work again. It seems the integration only works during 10 minutes after the reload.

Daniel is aware of these issues and he is going to take a look in the next 2-3 days. So we must wait and let him to do his magic. 😊

**Comment by monogalactico** [comment]
Other discussions with similar problems... In my case after a short time all sensors change to "Unknown". Domain amazon.es and 2FA... I Have aire monitoring and several echos with temperature sensors....

**Comment by vjbalex** [comment]
I have updated everytging I can think of but tempurature sensors still do not survive am HA restart. After a restart I must delete the Integration entity and reset it up again. Very tiring...
OS Version:               Home Assistant OS 13.0
Home Assistant Core:      2024.8.2
Home Assistant Supervisior:    2024.08.0
Alexa Media Player: 4.12.9
AlexaPy Version: 1.29.0
edited line in /config/custom_components/alexa_media/manifest.json:
"requirements": ["alexapy==1.29.0", "packaging>=20.3", "wrapt>=1.14.0"],

Are there any other remedies to try?

**Comment by figorr** [comment]
I want to update my experience. Seems it has been solved.

First of all … I am running Supervisor and my domain is Amazon.es.

In order to be able to run some automations, some days ago I decided to downgrade and to restore an old backup to 2024.7.4. In this backup I was running AMP. 4.12.7 and everything was running OK after the restoration. All the temperature sensors and Last Called Service too.

During the following days, every time I saw a new AMP update … I installed the new update and everything seems Ok under 2024.7.4 … so finally yesterday I updated to 4.12.10.

Today I saw some new updates (esphome… and OS 13.1). I decided to apply all these updates and after restarting HA everything still worked OK under Supervisor 2024.7.4.
Even I updated HACS to the new 2.0 version without any problem. 
Multiple restarts between updates and everything was running smoothly.

I decided to make a new backup of my 2024.7.4 setup before applying the 2024.8.2 core version.

After this new backup I installed the 2024.8.2 Core.

Once the restart was finished I saw the integration asked for a reconfiguration. I followed the usual steps (OTP code …) as always … but the process showed error at the end although the reconfiguration warning disappeared  and the integration seems to work. I went to logs and I could see a couple of warnings one regarding the pickle file could not be removed and asked for a manual remove and another one about Alexa notify could not be unloaded.

Before doing anything else I decided to wait 10 minutes in order to see if the integration fails. And It failed after 10 minutes. And I could see at log a warning about Unauthorized Access or Login when trying to get the records. So I went to the .storage folder and I deleted the pickle file and then I restarted HA.

After the restart I hadn’t had to reconfigure AMP and I didn’t see any new warnings at logs related to AMP. More than 1 hour since this and all the temperature sensors from the Echos are still available and updating values without warnings at logs. Even the last called service is being updated (every 10 minutes or manually by calling the service).

It is a bit late now in Spain … so let’s see if tomorrow morning when I wake up everything is still working OK. 😊

I wanted to share my experience just in case is useful for anyone else.

**Comment by figorr** [comment]
Unfortunately this morning the integration had failed.

The reload make it work again during a while. But now just for 10 min.

After the reload I can find a couple of warnings at logs.

Warning 1
```
Este error se originó a partir de una integración personalizada.

Registrador: custom_components.alexa_media
Fuente: custom_components/alexa_media/__init__.py:1345
integración: Alexa Media Player (documentación, problemas)
Ocurrió por primera vez: 07:12:04 (1 ocurrencias)
Último inicio de sesión: 07:12:04

Could not remove cookiefile: /config/.storage/alexa_media.***.pickle. Please manually delete the file.
```

Warning 2
```
Registrador: homeassistant.config_entries
Fuente: config_entries.py:819
Ocurrió por primera vez: 07:12:03 (1 ocurrencias)
Último inicio de sesión: 07:12:03

Error unloading entry Alexa for notify
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 819, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 135, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

**Comment by monogalactico** [comment]
Good morning. Similar  case. I reinstalled (and clean cache, erase cookie, etc) and at 3:00 Am I had Unknown all sensors and I found in log 

--------

Log details (ERROR)


Logger: homeassistant.config_entries
Source: config_entries.py:819
First occurred: 3:08:27 AM (1 occurrences)
Last logged: 3:08:27 AM

Error unloading entry xxxxx@xxxx.com - amazon.es for notify
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 819, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 135, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

I've reinitiated and I changed scan from 60 to 600... Let's see...

**Comment by monogalactico** [comment]
Next log line after this error is this warning about cookie file:

Logger: custom_components.alexa_media
Source: custom_components/alexa_media/__init__.py:1345
integration: Alexa Media Player ([documentation](https://github.com/alandtse/alexa_media_player/wiki), [issues](https://github.com/alandtse/alexa_media_player/issues))
First occurred: 3:08:27 AM (1 occurrences)
Last logged: 3:08:27 AM

Could not remove cookiefile: /config/.storage/alexa_media.xxxx@xxxx.com.pickle. Please manually delete the file.

**Comment by figorr** [comment]
It looks both things are related. At first I noticed the temperature sensors became unavailable ... but then I also noticed the last_called_service didn't work too. And then that tts failed too.

I tried what daniel proposed at this post ... [https://github.com/alandtse/alexa_media_player/issues/2275#issuecomment-2298014602](url)

@monogalactico You can try to replace the `__init__.py` file with the new one from the zip file daniel upload at that post. He was asking for some testers.  It didn't work for me. And I received the same warnings at log but maybe is different for you or you receive a different error.

**Comment by danielbrunt57** [comment]
Closing this as it's the same error message as #2453.  Please use that issue for ongoing discussion.
