### ISSUE TITLE
Sign in prompt is not going through

### ISSUE THREAD

**Issue by sachinvaishnav** [alandtse/alexa_media_player#2542]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

I have HACS integration installed successfully to my HA version 2024.9.2. When I am trying to login with my Amazon authentication pop up it keeps bringing back the sign in prompt. Its not going through the next steps. 

**To Reproduce**

1. Install HACS > Alexa integration 
2. Restart HA
3. Go to HA > Integration > Alexa media player
4. Provide authentication details (amazon.in, email id, password)
5. Submit the form
6. Auth page appears. Provide your Amazon sign in email
7. Click sign in
8. Enter Password 
9. Click submit

**Expected behavior**

It should login and authenticate the integration. But its coming back to the same login screen. 

**Screenshots**

**System details**

- Home Assistant version: 2024.9.2
- alexa_media version (from `const.py` or HA startup log): v4.13.1
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by ziolelle** [comment]
No more possible to authenticate using the same Home Assistant and Alexa_media 
Trying to reauthenicate through Settings-> Devices and Services -> Alexa Media Player 
The Integration is in Red telling "Needs Attention" 
Cloicking on 3 verical dots -> Reload 
it not working giving in Log two entries:

`alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7fba7e74a090>,), {'cookies': {}}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('can only concatenate str (not "NoneType") to str',)`

and

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 10:54:01 (1 occurrences)
Last logged: 10:54:01

Error setting up entry ziolelle@yahoo.com - amazon.it for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 671, in login
    site = await self._process_page(html, site)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 1506, in _process_page
    error_message += list_item.find("span").string
TypeError: can only concatenate str (not "NoneType") to str

```

**Comment by dadeboni** [comment]
Same is happening to me, I have removed the integration and reinstalled and still not able to authenticate

**Comment by plopezllorca** [comment]
There is a workaround that worked for me:

https://github.com/alandtse/alexa_media_player/issues/2514#issuecomment-2345070532

**Comment by apizzoni** [comment]
Thanks, @plopezllorca, indeed by following what @danielbrunt57 wrote, it is possible to configure the integration from scratch, but then it stops working after a few minutes. Only if reinitialized, when using TTS you can hear Alexa 'speak'... Does this happen to you too?

**Comment by plopezllorca** [comment]
Yes, I have the same problem. I heard about a workaround for that issue, but I don´t like very much... 😕

https://github.com/alandtse/alexa_media_player/issues/2514#issuecomment-2358260991

**Comment by ForTheRush** [comment]
same. tried deleting the integration and reading it but same inability to login

**Comment by dadeboni** [comment]
I tried the workaround referenced and still no luck

**Comment by danielbrunt57** [comment]
> No more possible to authenticate using the same Home Assistant and Alexa_media Trying to reauthenticate through Settings-> Devices and Services -> Alexa Media Player The Integration is in Red telling "Needs Attention" Clicking on 3 vertical dots -> Reload it not working giving in Log two entries:
  
Your problem is not relevant here.

**Comment by danielbrunt57** [comment]
The problem is the new three page login sequence with email, then password, then 2SV
AMP was programmed to do the callback after two pages (the way the Amazon login used to be) but gets an "unsuccessful" response after only two pages since the login sequence did not finish all three pages and AMP returns you to the previous (first) page to try again.  So...

At this screen, select the first option

![image](https://github.com/user-attachments/assets/b27707da-b7ae-4e09-ba90-28bdc9060d79)
 
Enter "x x" for First and last name and click CREATE YOUR AMAZON ACCOUNT

![image](https://github.com/user-attachments/assets/1d11afea-041e-422c-a254-460500c41fa3)

When that fails, select Sign in Already a customer?

![image](https://github.com/user-attachments/assets/df500cf4-d83a-43d4-b8d5-60d3310a9464)

The page then changes to show both email & password on the same page. (which is still the first page in the callback sequence)

![image](https://github.com/user-attachments/assets/44130c89-5dd3-4404-99bf-d59676d865e3)

Now you can select SIGN IN which then proceeds to the 2nd page which is Two-Step Verification
and the callback to HA will then occur where it will test if your email, password & OTP login was successful or not. 
If not, it sends you back to the first page in Amazon's new 3 page sequence.

![image](https://github.com/user-attachments/assets/99c02188-6405-4c30-ac81-ceddbcc6818f)

**Comment by danielbrunt57** [comment]
Duplicate.  See issue [#2514](https://github.com/alandtse/alexa_media_player/issues/2514)
