### ISSUE TITLE
Error After Upgrade to 2024.12.0

### ISSUE THREAD

**Issue by BobRathke** [alandtse/alexa_media_player#2719]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ]
(https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Media Player Fails to Start

**To Reproduce**

Start the server. Rebooted several times.
**System details**

- Home Assistant version: 2024.12.0
- alexa_media version (from `const.py` or HA startup log): 5.0.0
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y

Error in Logs:

2024-12-04 22:00:12.302 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies:
  ╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and
      aiofiles>=24.1.0, we can conclude that alexapy==1.29.4 cannot be used.
      And because you require alexapy==1.29.4, we can conclude that your
      requirements are unsatisfiable.
2024-12-04 22:00:13.612 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies:
  ╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and
      aiofiles>=24.1.0, we can conclude that alexapy==1.29.4 cannot be used.
      And because you require alexapy==1.29.4, we can conclude that your
      requirements are unsatisfiable.
2024-12-04 22:00:15.126 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies:
  ╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and
      aiofiles>=24.1.0, we can conclude that alexapy==1.29.4 cannot be used.
      And because you require alexapy==1.29.4, we can conclude that your
      requirements are unsatisfiable.
2024-12-04 22:00:15.269 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].

**Comment by ingo916** [comment]
Same issue for me

**Comment by shackrat** [comment]
Same issue here as well..

`Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 10:16:20 PM (6 occurrences)
Last logged: 10:16:47 PM

Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies: ╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and aiofiles>=24.1.0, we can conclude that alexapy==1.29.4 cannot be used. And because you require alexapy==1.29.4, we can conclude that your requirements are unsatisfiable.
Unable to install package pyatv==0.10.0: × No solution found when resolving dependencies: ╰─▶ Because pyatv==0.10.0 depends on protobuf>=3.19.1,<4 and protobuf==5.28.3, we can conclude that pyatv==0.10.0 cannot be used. And because you require pyatv==0.10.0, we can conclude that your requirements are unsatisfiable.`

**Comment by cevfarias** [comment]
Same issue here as well!

**Comment by danielbrunt57** [comment]
> IMPORTANT: Please search the issues

Duplicate.
