### ISSUE TITLE
Integration won't start after 2024.12.0 update

### ISSUE THREAD

**Issue by bkr1969** [alandtse/alexa_media_player#2723]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

Doesn't load

**To Reproduce**

1. Update to 2024.12.0

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 06:10:32 (1 occurrences)
Last logged: 06:10:32

Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].

**Additional context**

I imagine this has something to do with the python update that was included in this core.

**Comment by btrudgill** [comment]
Please search the open issues before duplicating. This is a well known issue, [here](https://github.com/alandtse/alexa_media_player/issues/2698).

**Comment by otaviojr** [comment]
Yes, but this time is a little bit more difficult... until now, I always used this post to solve it... no happening anymore...

It just doesn't get up...

**Comment by otaviojr** [comment]
> Please search the open issues before duplicating. This is a well known issue, [here](https://github.com/alandtse/alexa_media_player/issues/2698).

Yes, but this time is a little bit more difficult... until now, I always used this post to solve it... no happening anymore...

It just doesn't get up...

**Comment by HarryBouch96** [comment]
same

**Comment by bmitchell76** [comment]
same

**Comment by yigitgungor** [comment]
"Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies: ╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and aiofiles>=24.1.0, we can conclude that alexapy==1.29.4 cannot be used. And because you require alexapy==1.29.4, we can conclude that your requirements are unsatisfiable."

**Comment by ParabolicArts** [comment]
Same problem:

Registrador: homeassistant.setup
Fuente: setup.py:269
Ocurrió por primera vez: 17:39:57 (1 ocurrencias)
Última vez registrado: 17:39:57

Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].


Registrador: homeassistant.util.package
Fuente: util/package.py:152
Ocurrió por primera vez: 17:39:56 (3 ocurrencias)
Última vez registrado: 17:39:57

Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies: ╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and aiofiles>=24.1.0, we can conclude that alexapy==1.29.4 cannot be used. And because you require alexapy==1.29.4, we can conclude that your requirements are unsatisfiable.

**Comment by DLThompson06** [comment]
same

**Comment by Hugo280561** [comment]
Same

**Comment by tonyis49** [comment]
Same here

**Comment by mikeaumiller** [comment]
Same same

**Comment by WxrthlessLiquid** [comment]
Same here. Probably same fault-source as I just updated yesterday and today I got multiple error-messages from my automations that alexa_media_player is not known as command, and then I found out that Alexa Media Player doesn't load ("Nicht geladen").

Currently I am trying to reverse/restore from a backup before I made the update, looking forward that they find a solution to come up to fix this kind of problem.

**Comment by WxrthlessLiquid** [comment]
> Same here. Probably same fault-source as I just updated yesterday and today I got multiple error-messages from my automations that alexa_media_player is not known as command, and then I found out that Alexa Media Player doesn't load ("Nicht geladen").
> 
> Currently I am trying to reverse/restore from a backup before I made the update, looking forward that they find a solution to come up to fix this kind of problem.

I managed to get it to work again, thanks god. So restoring from backup seems to get it back to work.

**Comment by erictroebs** [comment]
Downgrading the version seems only work if the lower version is already present in the system, which did not work for my docker container. But there is a new version `1.29.5` of `alexapy`.

- edit `custom_components/alexa_media/manifest.json` and change `alexapy==1.29.4` to `alexapy==1.29.5`
- restart HA

This works for me until a new update of this repo is released.

**Comment by GlenWi** [comment]
Thanks erictroebs - change to 1.29.5 worked for me.

**Comment by Albrecht1954** [comment]
yes, it's running after changeing alexapy

**Comment by elyobelyob** [comment]
Now I'm posting a comment .. chill Winston .. it all gets fixed quickly ...

Thanks to all the efforts, and not the mud slingers.

**Comment by danielbrunt57** [comment]
> it all gets fixed quickly

I was trying to get it resolved before 2024.12.0 hit the streets but alas, I/we missed the mark. 
Kudos to contributor @bieniu whose MR made the cut before mine!
