### ISSUE TITLE
Media Wont Stream to Alexa Devies

### ISSUE THREAD

**Issue by Abe-Telo** [alandtse/alexa_media_player#2729]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When attempting to play music from ytubeMediaPlayer (YouTube) i get a announcement: To send TTS, please set Announce=true. Music can't be played this way.

  
**System details**

- Home Assistant version: 
 Core 2024.12.0
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.4

 Here is the log.
Logger: custom_components.alexa_media.media_player
Source: custom_components/alexa_media/media_player.py:1436
integration: Alexa Media Player ([documentation](https://github.com/alandtse/alexa_media_player/wiki), [issues](https://github.com/alandtse/alexa_media_player/issues))
First occurred: 2:37:58 AM (4 occurrences)
Last logged: 2:39:13 AM
To send TTS, please set Announce=true. Music can't be played this way.

**Comment by Reachushere** [comment]
Same issue using Music Assistant

**Comment by sayam93** [comment]
I believe this Custom Integration acts as a middleman that allows Home Assistant to communicate with Amazon servers over the cloud by interacting with the APIs available from Amazon side. The amazon servers act as gatekeepers to the Alexa ecosystem and have to let through the data received from Home Assistant (or ytubeMediaPlayer) using the API to the Alexa device. 

So, being the gatekeeper of what is allowed to be played on the Alexa device, Amazon has to provide a method to allow it to stream content other than TTS which I believe it no longer does.

The other approach involve using an Alexa skill but it only allows you to ask your Alexa device to play music using that skill. It still does not allow you to stream directly from the service providing the skill (like Spotify) to the Alexa device.

I hope that helps understand things better.

**Comment by Sinaloit** [comment]
https://github.com/alandtse/alexa_media_player/blob/a39db58bd9ad3db19eacf90494788116c2f5ed1f/custom_components/alexa_media/media_player.py#L1450-L1456
The above seems to send music requests to async_play_tts_cloud_say which at the bottom sends out the error message mentioned in this issue.  Not sure why the actual play_music call is only the default action and not used when the media_type is music. https://github.com/alandtse/alexa_media_player/blob/a39db58bd9ad3db19eacf90494788116c2f5ed1f/custom_components/alexa_media/media_player.py#L1585-L1613

**Comment by sayam93** [comment]
> https://github.com/alandtse/alexa_media_player/blob/a39db58bd9ad3db19eacf90494788116c2f5ed1f/custom_components/alexa_media/media_player.py#L1450-L1456
> 
> 
> The above seems to send music requests to async_play_tts_cloud_say which at the bottom sends out the error message mentioned in this issue. Not sure why the actual play_music call is only the default action and not used when the media_type is music.
> https://github.com/alandtse/alexa_media_player/blob/a39db58bd9ad3db19eacf90494788116c2f5ed1f/custom_components/alexa_media/media_player.py#L1585-L1613

The first blob is simply a way to gracefully handle the error that arises when the media type is music instead of leaving the users clueless without a response at all. "Sorry folks! Amazon doesn't allow streaming music like this." would be a more appropriate TTS response for this I think.

Regarding the second blob, I think Amazon previously allowed this functionality and Alexa Media Player was able to use it (I started using Home Assistant only about a year ago so not sure) but the support no longer exists and this is just remnants of the old code that allowed it. It could also be some placeholder code they could use if Amazon allows/re-allows this functionality in the future.

**Comment by Sinaloit** [comment]
That play_music function in gitlab indicates you can pass a provider and search string, which _should_ work:
https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexaapi.py?ref_type=heads#L740-L741

Granted we'd need to pass some sort of valid provider, which would not likely work for local media but could be used for several services such as:

- Amazon Music
- Apple Music
- iHeartRadio
- Pandora
- TuneIn

**Comment by sayam93** [comment]
> That play_music function in gitlab indicates you can pass a provider and search string, which _should_ work: https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexaapi.py?ref_type=heads#L740-L741
> 
> Granted we'd need to pass some sort of valid provider, which would not likely work for local media but could be used for several services such as:
> 
> * Amazon Music
> * Apple Music
> * iHeartRadio
> * Pandora
> * TuneIn

Thanks for explaining it in a better manner. You're right, it simply executes a search query which could be done with an automation like the one I am using (https://github.com/alandtse/alexa_media_player/issues/2208#issuecomment-2525321459).

Maybe the Music Assistant team could implement a way to pass a search query with 'custom' content type to the media player device created by AMP to create an illusion of the music being cast on the Alexa media device but even in that case, Alexa device would only be able to play the track if it is available on one of its supported services.

Therefore, this method still won't allow the media_player entity created by this Integration to be used like a proper media player using Music Assistant since this approach will limit the ability control playback fully or cast local media.
